common: &common
  adapter: mysql2
  database_timezone: local
  pool: 100
  password: password
  connect_timeout: 20
  timeout: 900
  socket: /tmp/mysql.sock
  port: 3306
  username: root
  password: Forever720
development:
  <<: *common
  adapter: mysql2
  database: code_test
